[colors]
draw_bold_text_with_bright_colors = false

[cursor]
blink_interval = 750
[cursor.style]
shape = "Block"
blinking = "On"

[env]
WINIT_UNIX_BACKEND = "x11"
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 14.0

[font.bold]
family = "JetBrains Mono Nerd Font"

[font.bold_italic]
family = "JetBrains Mono Nerd Font"

[font.italic]
family = "JetBrains Mono Nerd Font"

[font.normal]
family = "JetBrains Mono Nerd Font"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[scrolling]
history = 80000

[window]
decorations = "full"
opacity = 1.0

[general]
# import = ["/home/zafer/.config/alacritty/themes/ayu_dark.toml"]
# import = ["/home/zafer/.config/alacritty/themes/gruvbox_dark.toml"]
# import = ["/home/zafer/.config/alacritty/themes/gruvbox_light.toml"]
# import = ["/home/zafer/.config/alacritty/themes/alabaster.toml"]
# import = ["/home/zafer/.config/alacritty/themes/alabaster_dark.toml"]
# import = ["/home/zafer/.config/alacritty/themes/nordic.toml"]
import = ["/home/zafer/.config/alacritty/github_monochrome/github_monochrome_light.toml"]
